# Helm template
inject:
  enabled: true
  # Config contains the configuration files ca.json and defaults.json
  config:
    files:
      ca.json:
        root: /home/step/certs/root_ca.crt
        federateRoots: []
        crt: /home/step/certs/intermediate_ca.crt
        key: /home/step/secrets/intermediate_ca_key
        address: :9000
        dnsNames:
          - devca.test.com
        logger:
          format: json
        db:
          type: badgerv2
          dataSource: /home/step/db
        authority:
          provisioners:
            - {"type":"JWK","name":"admin@test.com","key":{"use":"sig","kty":"EC","kid":"EleWjlP7ARi1K04A3UH2lLXN0Y42yZ0ipxEmHDtrW3U","crv":"P-256","alg":"ES256","x":"L3gg1NqAcJQiEQMqQV-RC0ssT-sdKKMl8Rq70w_-xZg","y":"AiMCxtbG2Jgu3Ub5uut4uBvWnm3KUYglCAJLapYk45Y"},"encryptedKey":"eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjEwMDAwMCwicDJzIjoiOVdzTFRmNGdmWm5BT1RuQXFtbzkwZyJ9.ekLasXkQzB9J8dLfpCaGoHktj13PPzKYx7eMMKG1xs3-w4TlMvccRQ.0Z2R9It-HaKywAea.MmOmRfLgTdO6VqC6lpWd55xVpHy-F7N0HjPquXtdMyG8IfZZpCpOBVE5ltPMYhUunfALwxUe9zT8vqK86oZeOUvvd4PHRO3FT7UkvX6fb7EGFya3aoV0paHpYH9Ee9Ph4ERqYqmrvMQe1W48r6u2rthRWKmjm_PglQI-KEP4_snB4V1G4E-Z1uI9WmguK3ur0WXeohrdiIkKTYJylh1MFKFKCrZPpl0BKuTPK5b2xjzJuZQOuvSe2EXgCjAKNKRCyFBs46aMJyd5gwb1dFW3tCRLilQlJ0vNsBaPn_raQBXH6kOCPLNysvMFrTc2iUY4jZ6703OIVlgTByhfSMQ.cejde8lPNXeEn4i_fIylfg","options":{"x509":{},"ssh":{}}}
        tls:
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          minVersion: 1.2
          maxVersion: 1.3
          renegotiation: false

      defaults.json:
        ca-url: https://devca.test.com
        ca-config: /home/step/config/ca.json
        fingerprint: fcc1057a042bf941b83f9c430ce287124289a31b3731a6348e7e16cba0a06fe3
        root: /home/step/certs/root_ca.crt

  # Certificates contains the root and intermediate certificate and 
  # optionally the SSH host and user public keys
  certificates:
    # intermediate_ca contains the text of the intermediate CA Certificate
    intermediate_ca: |
      -----BEGIN CERTIFICATE-----
      MIIBtTCCAVugAwIBAgIRAOteoqsChkvM3woF1dI5Q54wCgYIKoZIzj0EAwIwJDEM
      MAoGA1UEChMDZGV2MRQwEgYDVQQDEwtkZXYgUm9vdCBDQTAeFw0yMjA2MTQxNDIy
      MTdaFw0zMjA2MTExNDIyMTdaMCwxDDAKBgNVBAoTA2RldjEcMBoGA1UEAxMTZGV2
      IEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDqbp6yX
      zqtvB2FaVN4X03H0oj0rz9X7CZg5ecPGDgD0SF2rBc5X+9hXi+X/2Vl+4tlRxEua
      GI54srUrkBkA9S2jZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
      AgEAMB0GA1UdDgQWBBT+epamBfDFmNHO2uYdPiyu8dgx8zAfBgNVHSMEGDAWgBRu
      F/W0DG1qG69m4qO6FnH9bIzQnzAKBggqhkjOPQQDAgNIADBFAiASp8JfWUC7jBFs
      A3XnC6njBLCQG+lUu3AhGFG1+ztt0gIhANOXNCJapiomwlInOBzcK/xhM+jMsKoa
      hZvGzTkmB+sU
      -----END CERTIFICATE-----
      
      
    # root_ca contains the text of the root CA Certificate
    root_ca: |
      -----BEGIN CERTIFICATE-----
      MIIBizCCATGgAwIBAgIQJoWWquesHvvhqIefjhEpITAKBggqhkjOPQQDAjAkMQww
      CgYDVQQKEwNkZXYxFDASBgNVBAMTC2RldiBSb290IENBMB4XDTIyMDYxNDE0MjIx
      NloXDTMyMDYxMTE0MjIxNlowJDEMMAoGA1UEChMDZGV2MRQwEgYDVQQDEwtkZXYg
      Um9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFcwYhs/d5A/PTnpC+LB
      latXYUuIddgSIg/Im6k/+jJ3/WrYLC9UhDNjMiEIKeOjhtj12QWQEejNEia96Vo3
      m2KjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1Ud
      DgQWBBRuF/W0DG1qG69m4qO6FnH9bIzQnzAKBggqhkjOPQQDAgNIADBFAiA4hdcV
      OGEiN2x0CFycENn1aQhhfbfGuppvaVbxPWOEZgIhAKKIy5cCEjwsqCO2xW9HQJpW
      HaLOI7lB4uPGc8hL5B1J
      -----END CERTIFICATE-----
      

  # Secrets contains the root and intermediate keys and optionally the SSH
  # private keys
  secrets:
    # ca_password contains the password used to encrypt x509.intermediate_ca_key, ssh.host_ca_key and ssh.user_ca_key
    # This value must be base64 encoded.
    ca_password: 
    provisioner_password: 

    x509:
      # intermediate_ca_key contains the contents of your encrypted intermediate CA key
      intermediate_ca_key: |
        -----BEGIN EC PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-256-CBC,0f65b082646410c3881279603186fc8d
        
        NAFrKXwPKAQ5kslUENv4/TQfvVoA/PWy1QNb0D72LUYCxf54LYyziFXqk4QBTpI5
        lRwCqBM0MlABlTE5oTbxVjDhG2ZYrIN45CX4YkZLE/5fT31FqwyYklzx6Hk+5/yl
        Xzv0wnGO+vy9fkcgerdbVeT4DNhrPcI+b1fUd8Nl2p0=
        -----END EC PRIVATE KEY-----
        

      # root_ca_key contains the contents of your encrypted root CA key
      # Note that this value can be omitted without impacting the functionality of step-certificates
      # If supplied, this should be encrypted using a unique password that is not used for encrypting
      # the intermediate_ca_key, ssh.host_ca_key or ssh.user_ca_key.
      root_ca_key: |
        -----BEGIN EC PRIVATE KEY-----
        Proc-Type: 4,ENCRYPTED
        DEK-Info: AES-256-CBC,19692961a4059f191334a32da6d416c6
        
        ZzgVmhiWH014ym6unOuBg1H0BuFHePTMSCI3flSykUEJVP+7VQ+l6oCmrqFNArT4
        H/2eB6M/PXVz2XMucbgBdqsc4mAvhMAeiW3m4rqmbiHSVNzbHOM0U1TsKlsIMAS5
        sb6h69fglfeQXxSFSm5Y8l5Ptv1j0wbZoMs7DfAqpTc=
        -----END EC PRIVATE KEY-----
        
